---
- name: PHP Debug
  vars:
    msg: |-
      bsd_php_role_version: {{ bsd_php_role_version }}
      ansible_architecture: {{ ansible_architecture }}
      ansible_os_family: {{ ansible_os_family }}
      ansible_distribution: {{ ansible_distribution }}
      ansible_distribution_major_version: {{ ansible_distribution_major_version }}
      ansible_distribution_version: {{ ansible_distribution_version }}
      ansible_distribution_release: {{ ansible_distribution_release }}
      ansible_python_version: {{ ansible_python_version }}

      ansible_local.php.version: {{ ansible_local.php.version }}

      freebsd_install_method: {{ freebsd_install_method }}
      freebsd_use_packages: {{ freebsd_use_packages | d('UNDEFINED') }}
      bsd_php_pkg_install: {{ bsd_php_pkg_install }}
      bsd_php_packages:
        {{ bsd_php_packages | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_packages_extra:
        {{ bsd_php_packages_extra | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_backup: {{ bsd_php_backup }}

      bsd_phpfpm_enable: {{ bsd_phpfpm_enable }}
      bsd_phpfpm_service: {{ bsd_phpfpm_service }}
      bsd_phpfpm_wait_enable: {{ bsd_phpfpm_wait_enable }}

      bsd_php_conf_owner: {{ bsd_php_conf_owner }}
      bsd_php_conf_group: {{ bsd_php_conf_group }}
      bsd_php_conf_mode: {{ bsd_php_conf_mode }}
      bsd_php_conf_path: {{ bsd_php_conf_path }}
      bsd_php_conf_file: {{ bsd_php_conf_file }}
      bsd_php_conf:
        {{ bsd_php_conf | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_conf_fpm_file: {{ bsd_php_conf_fpm_file }}
      bsd_php_conf_fpm:
        {{ bsd_php_conf_fpm | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_conf_ini_file: {{ bsd_php_conf_ini_file }}
      bsd_php_conf_ini:
        {{ bsd_php_conf_ini | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_conf_phpd:
        {{ bsd_php_conf_phpd | to_nice_yaml(indent=2) | indent(2) }}
      bsd_php_conf_www_listen_url: {{ bsd_php_conf_www_listen_url }}
      bsd_php_conf_www_listen_sock: {{ bsd_php_conf_www_listen_sock }}
      bsd_php_conf_www_listen: {{ bsd_php_conf_www_listen }}
      bsd_php_conf_fpmd:
        {{ bsd_php_conf_fpmd | to_yaml(indent=2) | indent(2) }}
      bsd_php_rcconf:
        {{ bsd_php_rcconf | to_yaml(indent=2) | indent(2) }}

  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
